[buildPlans.pragmasevka]
family = "Pragmasevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

hintParams = ["-a", "qqq"]   

    [buildPlans.pragmasevka.widths.normal]
    shape = 500
    menu  = 5
    css   = "normal"

    [buildPlans.pragmasevka.metric-override]
    leading = 1100
    xHeight = 550

    [buildPlans.pragmasevka.ligations]
    inherits="default-calt"
    enables = [
        "eqslasheq",
        "kern-dotty",
        "kern-bars",
        "llggeq",
        "connected-underscore", 
        "connected-number-sign",
        "connected-hyphen"
    ]
    disables = ["slash-asterisk"]

    [buildPlans.pragmasevka.variants]
    inherits = "ss08"

    [buildPlans.pragmasevka.weights.regular]
    shape = 425
    menu = 400
    css = 400

    [buildPlans.pragmasevka.weights.semibold]
    shape = 600
    menu = 600
    css = 600
    
    [buildPlans.pragmasevka.weights.bold]
    shape = 800
    menu = 700
    css = 700

    [buildPlans.pragmasevka.weights.black]
    shape = 900
    menu = 900
    css = 900

    [buildPlans.pragmasevka.slopes]
    upright = "default.Upright"
    italic = "default.Italic"
